config/routes.rb
Rails.application.routes.draw do
  root to: 'characters#index'
  devise_for :users
  resources :actors
  resources :animes
  resources :characters
  resources :anime_characters
  resources :actor_characters
  get 'messages/new' => 'messages#new'
  post 'messages' => 'messages#create'
  get 'comparisons/index'
  get 'comparisons/show'
end

app/models/actor.rb
class Actor < ApplicationRecord
  validates :sh_name, presence: true

  has_many :actor_characters, dependent: :destroy
  has_many :characters, through: :actor_characters
  has_many :actor_animes, dependent: :destroy
  has_many :anime, through: :actor_animes

  def character(anime)
    characters.select { |character| character.anime.include?(anime) }
  end
end

app/models/actor_anime.rb
class ActorAnime < ApplicationRecord
  validates :actor_id, :anime_id, presence: true
  belongs_to :actor
  belongs_to :anime
end

app/models/actor_character.rb
class ActorCharacter < ApplicationRecord
  validates :actor_id, :character_id, presence: true
  belongs_to :actor
  belongs_to :character
end

app/models/anime.rb
class Anime < ApplicationRecord
  validates :title, presence: true

  has_many :anime_characters, dependent: :destroy
  has_many :characters, through: :anime_characters
  has_many :actor_animes, dependent: :destroy
  has_many :actors, through: :actor_animes
end

app/models/anime_character.rb
class AnimeCharacter < ApplicationRecord
  validates :anime_id, :character_id, presence: true
  belongs_to :anime
  belongs_to :character
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  validates :name, presence: true

  has_many :actor_characters, dependent: :destroy
  has_many :anime_characters, dependent: :destroy
  has_many :actors, through: :actor_characters
  has_many :anime, through: :anime_characters

  def actor(anime)
    actors.select { |actor| actor.anime.include?(anime) }
  end

  def s_anime(actor)
    anime.select { |anime| anime.actors.include?(actor) }
  end
end

app/models/comparison.rb
# frozen_string_literal: true

class Comparison
  include ActiveModel::Model
  attr_accessor :actor_ids, :actor1, :actor2
  validates :actor_ids, presence: true, length: { is: 3 }

  def set_actors
    @actor1 = Actor.find(actor_ids[1])
    @actor2 = Actor.find(actor_ids[2])
  end

  def co_animation
    set_actors
    @actor1.anime & @actor2.anime
  end
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :account, :body
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :set_actor, only: %i[show edit update destroy]
  def index
    @q = Actor.ransack(params[:q])
    @actors = @q.result(distinct: true).page(params[:page])
  end

  def show; end

  def edit; end

  def update
    if @actor.update(actor_params)
      redirect_to @actor, notice: 'successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @actor.destroy
    redirect_to root_path
  end

  private

  def set_actor
    @actor = Actor.find(params[:id])
  end

  def actor_params
    params.require(:actor).permit(:name)
  end
end

app/controllers/animes_controller.rb
class AnimesController < ApplicationController
  before_action :set_anime, only: %i[show edit update destroy]

  def index
    @q = Anime.ransack(params[:q])
    @animes = @q.result(distinct: true).page(params[:page])
  end

  def show; end

  def edit; end

  def update
    if @anime.update(anime_params)
      redirect_to @anime, notice: 'successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @anime.destroy
    redirect_to root_path
  end

  private

  def set_anime
    @anime = Anime.find(params[:id])
  end

  def anime_params
    params.require(:anime).permit(:title)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: %i[show edit update destroy]

  def index
    @q = Character.ransack(params[:q])
    @characters = @q.result(distinct: true).page(params[:page])
  end

  def show
    @animes = @character.anime
    @actors = @character.actors
  end

  def edit; end

  def update
    if @character.update(character_params)
      redirect_to @character, notice: 'successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @character.destroy
    redirect_to root_path
  end

  private

  def set_character
    @character = Character.find(params[:id])
  end

  def character_params
    params.require(:character).permit(:name, :profile)
  end
end

app/controllers/comparisons_controller.rb
class ComparisonsController < ApplicationController
  def index
    @actors = Actor.all
    @comparison = Comparison.new
  end

  def show
    @comparison = Comparison.new(comparison_params)
    if @comparison.valid?
      @co_anime = @comparison.co_animation
    else
      @actors = Actor.all
      render :index
    end
  end

  private

  def comparison_params
    params.require(:comparison).permit(actor_ids: [])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    if @message.valid?
      MessageMailer.contact(@message).deliver_now
      flash[:notice] = "メッセージを送ってくださりありがとうございます。改善に役立てます。"
      redirect_to root_path
    else
      flash[:notice] = "内容を記入してください。"
      render :new
    end
  end

  private

  def message_params
    params.require(:message).permit(:account, :body)
  end
end

app/helpers/actor_characters_helper.rb
module ActorCharactersHelper
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/anime_characters_helper.rb
module AnimeCharactersHelper
end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/comparisons_helper.rb
module ComparisonsHelper
end

app/views/actors/_form.html.erb
<div class="w-5/6 lg:w-full max-w-md mx-auto my-8">
  <%= form_with(model: actor, local: true, class: 'bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4') do |form| %>
    <% if actor.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(actor.errors.count, "error") %> prohibited this actor from being saved:</h2>

        <ul>
          <% actor.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-4">
      <label class="block text-grey-darker text-sm font-bold mb-2">
        声優の名前
      </label>
      <%= form.text_field :sh_name, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline' %>
    </div>
    <div class="flex items-center justify-between">
      <%= form.submit '完了する', class: 'text-white font-semibold bg-grey-darkest hover:bg-black py-2 px-4 rounded focus:outline-none focus:shadow-outline' %>
      <div class="flex justify-between items-center">
        <%= link_to '戻る', actor, class: 'inline-block align-baseline font-bold text-sm text-grey-darkest hover:text-black' %>
        <% if user_signed_in? && current_user.admin? %>
          <%= link_to '削除', actor, class: 'text-white font-semibold bg-grey-darkest hover:bg-black ml-2 py-2 px-4 rounded focus:outline-none focus:shadow-outline', method: :delete, data: { confirm: '本当に削除しますか？' } %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/actors/edit.html.erb
<%= render partial: 'actors/form', locals: { actor: @actor } %>

app/views/actors/index.html.erb
<%= search_form_for @q, html: { class: 'max-w-sm w-5/6 m-auto my-4 lg:w-full' } do |f| %>
  <div class="flex items-center border-b border-b-2 border-grey-darkest py-2">
    <%= f.search_field :sh_name_cont, class: 'appearance-none bg-transparent border-none w-full text-grey-darkest mr-3 py-1 px-2 leading-tight focus:outline-none', placeholder: '声優さんの名前で検索'  %>
    <%= f.submit '検索', class: 'flex-no-shrink bg-grey-darkest hover:bg-black border-grey-darkest hover:border-black text-sm border-4 text-white py-1 px-2 rounded' %>
  </div>
<% end %>

<div class="w-5/6 mx-auto my-8 text-center">
  <%= link_to 'アニメ検索', animes_path, class: 'text-white text-bold bg-grey-darkest hover:bg-black rounded py-2 px-4' %>
  <%= link_to 'キャラ検索', characters_path, class: 'text-white text-bold bg-grey-darkest hover:bg-black rounded py-2 px-4' %>
</div>

<div class="flex flex-wrap lg:flex-col justify-start">
  <% @actors.find_each do |actor| %>
    <div class="max-w-md mx-auto my-2 w-5/6 lg:flex">
      <div class="border-b border-grey-darkest w-full py-2 leading-normal">
        <div class="text-black font-bold text-md">
          <%= link_to actor.sh_name, actor_path(actor) %>
        </div>
        <p class="text-grey-darker"><%#= actor.description %></p>
      </div>
    </div>
  <% end %>
</div>

<div class="w-5/6 mx-auto my-8 text-center">
  <%= link_to_prev_page @actors, '前のページ', class: 'text-white text-bold bg-grey-darkest hover:bg-black rounded py-2 px-4' %>
  <%= link_to_next_page @actors, '次のページ', class: 'text-white text-bold bg-grey-darkest hover:bg-black rounded py-2 px-4' %>
</div>

app/views/actors/show.html.erb
<div class="text-black font-bold text-xl w-5/6 m-auto my-4 text-center"><%= @actor.sh_name %>さん 登場キャラクター</div>
<% if user_signed_in? && current_user.admin? %>
  <div class="w-5/6 mx-auto my-8 text-center">
    <button class="bg-grey-darkest hover:bg-black font-semibold py-2 px-4 rounded-full">
      <%= link_to '編集する', edit_actor_path(@actor), class: 'text-white' %>
    </button>
  </div>
<% end %>
<div class="flex flex-wrap lg:flex-col justify-start">
  <% @actor.characters.each do |character| %>
    <div class="max-w-sm mx-auto my-2 w-5/6 lg:flex">
      <div class="border-b border-grey-darkest w-full py-2 leading-normal">
        <div class="text-black font-bold text-md"><%= link_to character.name, character_path(character) %></div>
        <p class="text-grey-darker"><%= character.s_anime(@actor)[0]&.title %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/animes/_form.html.erb
<div class="w-5/6 lg:w-full max-w-md mx-auto my-8">
  <%= form_with(model: @anime, local: true, class: 'bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4') do |form| %>
    <% if @anime.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@anime.errors.count, "error") %> prohibited this anime from being saved:</h2>

        <ul>
          <% @anime.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-4">
      <label class="block text-grey-darker text-sm font-bold mb-2">
        アニメの名称
      </label>
      <%= form.text_field :title, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline' %>
    </div>
    <div class="flex items-center justify-between">
      <%= form.submit '完了する', class: 'text-white font-semibold bg-grey-darkest hover:bg-black py-2 px-4 rounded focus:outline-none focus:shadow-outline' %>
      <div class="flex justify-between items-center">
        <%= link_to '戻る', anime_path(@anime), class: 'inline-block align-baseline font-bold text-sm text-grey-darkest hover:text-black' %>
        <% if user_signed_in? && current_user.admin? %>
          <%= link_to '削除', @anime, class: 'text-white font-semibold bg-grey-darkest hover:bg-black ml-2 py-2 px-4 rounded focus:outline-none focus:shadow-outline', method: :delete, data: { confirm: '本当に削除しますか？' } %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/animes/edit.html.erb
<%= render 'animes/form', character: @anime %>

app/views/animes/index.html.erb
<%= search_form_for @q, html: { class: 'max-w-sm w-5/6 m-auto my-4 lg:w-full' } do |f| %>
  <div class="flex items-center border-b border-b-2 border-grey-darkest py-2">
    <%= f.search_field :title_cont, class: 'appearance-none bg-transparent border-none w-full text-grey-darkest mr-3 py-1 px-2 leading-tight focus:outline-none', placeholder: 'アニメのタイトルで検索'  %>
    <%= f.submit '検索', class: 'flex-no-shrink bg-grey-darkest hover:bg-black border-grey-darkest hover:border-black text-sm border-4 text-white py-1 px-2 rounded' %>
  </div>
<% end %>

<div class="w-5/6 mx-auto my-8 text-center">
  <%= link_to 'キャラ検索', characters_path, class: 'text-white text-bold bg-grey-darkest hover:bg-black rounded py-2 px-4' %>
  <%= link_to '声優さん検索', actors_path, class: 'text-white text-bold bg-grey-darkest hover:bg-black rounded py-2 px-4' %>
</div>

<div class="flex flex-wrap lg:flex-col justify-start">
  <% @animes.find_each do |anime| %>
    <div class="max-w-md mx-auto my-2 w-5/6 lg:flex">
      <div class="border-b border-grey-darkest w-full py-2 leading-normal">
        <div class="text-black font-bold text-md mb-2">
          <%= link_to anime.title, anime_path(anime) %>
        </div>
        <p class="text-grey-darker"><%#= anime.description %></p>
      </div>
    </div>
  <% end %>
</div>

<div class="w-5/6 mx-auto my-8 text-center">
  <%= link_to_prev_page @animes, '前のページ', class: 'text-white text-bold bg-grey-darkest hover:bg-black rounded py-2 px-4' %>
  <%= link_to_next_page @animes, '次のページ', class: 'text-white text-bold bg-grey-darkest hover:bg-black rounded py-2 px-4' %>
</div>

app/views/animes/show.html.erb
<div class="text-black font-bold text-xl w-5/6 m-auto my-4 text-center"><%= @anime.title %> 登場キャラクター</div>
<% if user_signed_in? && current_user.admin? %>
<div class="w-5/6 mx-auto my-8 text-center">
  <button class="bg-grey-darkest hover:bg-black font-semibold py-2 px-4 rounded-full">
    <%= link_to '編集する', edit_anime_path(@anime), class: 'text-white' %>
  </button>
</div>
<% end %>
<div class="flex flex-wrap lg:flex-col justify-start">
  <% @anime.characters.each do |character| %>
    <div class="max-w-sm mx-auto my-2 w-5/6 lg:flex">
      <div class="border-b border-grey-darkest w-full py-2 leading-normal">
        <div class="text-black font-bold text-md mb-2"><%= link_to character.name, character_path(character) %></div>
        <p class="text-grey-darker"><%= character.actor(@anime)[0]&.sh_name %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/characters/_form.html.erb
<div class="w-5/6 lg:w-full max-w-md mx-auto my-8">
  <%= form_with(model: character, local: true, class: 'bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4') do |form| %>
    <% if user_signed_in? && current_user.admin? %>
    <div class="mb-4">
      <label class="block text-grey-darker text-sm font-bold mb-2">
        キャラクタの名前
      </label>
      <%= form.text_field :name, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline' %>
    </div>
    <% end %>
    <div class="mb-6">
      <label class="block text-grey-darker text-sm font-bold mb-2">
        プロフィール
      </label>
      <%= form.text_area :profile, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker mb-3 leading-tight focus:outline-none focus:shadow-outline resize-none', rows: 10 %>
    </div>
    <div class="flex items-center justify-between">
      <%= form.submit '完了する', class: 'text-white font-semibold bg-grey-darkest hover:bg-black py-2 px-4 rounded focus:outline-none focus:shadow-outline' %>
      <div class="flex justify-between items-center">
        <%= link_to '戻る', character_path(character), class: 'inline-block align-baseline font-bold text-sm text-grey-darkest hover:text-black' %>
        <% if user_signed_in? && current_user.admin? %>
          <%= link_to '削除', character, class: 'text-white font-semibold bg-grey-darkest hover:bg-black ml-2 py-2 px-4 rounded focus:outline-none focus:shadow-outline', method: :delete, data: { confirm: '本当に削除しますか？' } %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/characters/edit.html.erb
<%= render 'characters/form', character: @character %>

app/views/characters/index.html.erb
<%= search_form_for @q, html: { class: 'max-w-sm w-5/6 m-auto my-4 lg:w-full' } do |f| %>
  <div class="flex items-center border-b border-b-2 border-grey-darkest py-2">
    <%= f.search_field :name_cont, class: 'appearance-none bg-transparent border-none w-full text-grey-darkest mr-3 py-1 px-2 leading-tight focus:outline-none', placeholder: 'キャラクターの名前で検索'  %>
    <%= f.submit '検索', class: 'flex-no-shrink bg-grey-darkest hover:bg-black border-grey-darkest hover:border-black text-sm border-4 text-white py-1 px-2 rounded' %>
  </div>
<% end %>

<div class="w-5/6 mx-auto my-8 text-center">
  <%= link_to 'アニメ検索', animes_path, class: 'text-white text-bold bg-grey-darkest hover:bg-black rounded py-2 px-4' %>
  <%= link_to '声優さん検索', actors_path, class: 'text-white text-bold bg-grey-darkest hover:bg-black rounded py-2 px-4' %>
</div>

<div class="w-5/6 mx-auto my-8 text-center">
  <%= link_to '~ 声優さんを比較してみる ~', comparisons_index_path, class: 'text-white text-bold bg-grey-darkest hover:bg-black rounded py-2 px-4' %>
</div>

<div class="flex flex-wrap lg:flex-col justify-start">
  <% @characters.find_each do |character| %>
    <div class="max-w-sm mx-auto my-2 w-5/6 lg:flex">
      <div class="border-b border-grey-darkest w-full py-2 leading-normal">
          <div class="text-black font-bold text-md">
            <%= link_to character.name, character_path(character) %>
          </div>
          <p class="text-grey-darker"><%= character.actors[0]&.sh_name %> / <%= character.anime[0].title %></p>
      </div>
    </div>
  <% end %>
</div>

<div class="w-5/6 mx-auto my-8 text-center">
  <%= link_to_prev_page @characters, '前のページ', class: 'text-white text-bold bg-grey-darkest hover:bg-black rounded py-2 px-4' %>
  <%= link_to_next_page @characters, '次のページ', class: 'text-white text-bold bg-grey-darkest hover:bg-black rounded py-2 px-4' %>
</div>

app/views/characters/show.html.erb
<div class="max-w-md w-5/6 m-auto my-4 lg:flex">
  <div class="h-48 lg:h-auto lg:w-48 flex-none bg-cover rounded-t lg:rounded-t-none lg:rounded-l text-center overflow-hidden" style="background-image: url(<%= asset_path("back.jpg") %>)" title="Woman holding a mug">
  </div>
  <div class="w-full border-r border-b border-l border-grey-light lg:border-l-0 lg:border-t lg:border-grey-light bg-white rounded-b lg:rounded-b-none lg:rounded-r p-4 flex flex-col justify-between leading-normal">
    <div class="mb-8">
      <div class="text-black font-bold text-xl mb-2"><%= @character.name %></div>
      アニメ : <% @animes.each do |anime| %>
        <div class="text-black font-bold text-md mb-2"><%= link_to anime.title, anime_path(anime) %></div>
      <% end %>
      声優 : <% @actors.each do |actor| %>
        <div class="text-black font-bold text-md mb-2"> <%= link_to actor.sh_name, actor_path(actor) %></div>
      <% end %>
      プロフィール : <p class="text-black text-base"><%= @character.profile %></p>
    </div>
    <button class="bg-grey-darkest hover:bg-black font-semibold py-2 px-4 rounded-full">
      <%= link_to '編集する', edit_character_path(@character), class: 'text-white' %>
    </button>
  </div>
</div>

app/views/comparisons/index.html.erb
<div class="w-5/6 mx-auto my-8 text-center">
  <p>声優さんをふたり、選んでください。</p>
</div>

<%= form_with(model: @comparison, url: comparisons_show_path, method: :get, local: true, class: 'max-w-sm w-5/6 m-auto my-4 lg:w-full') do |form| %>
  <div class="flex justify-between items-center border-b border-b-2 border-grey-darkest py-2">
    <%= form.collection_select :actor_ids, @actors, :id, :sh_name, { include_blank: nil }, multiple: true, class: "form-control actor_search w-5/6" %>
    <%= form.submit '比較', class: 'ml-2 flex-no-shrink bg-grey-darkest hover:bg-black border-grey-darkest hover:border-black text-sm border-4 text-white py-1 px-2 rounded' %>
  </div>
<% end %>

app/views/comparisons/show.html.erb
<div class="text-black font-bold text-xl w-5/6 m-auto my-4 text-center">
  <%= link_to @comparison.actor1.sh_name, actor_path(@comparison.actor1) %>さん と <%= link_to @comparison.actor2.sh_name, actor_path(@comparison.actor2) %>さんの共演情報
</div>
<div class="flex flex-wrap lg:flex-col justify-start">
  <% @co_anime.each do |anime| %>
    <div class="max-w-sm mx-auto my-2 w-5/6 lg:flex">
      <div class="flex justify-between border-b border-grey-darkest w-full py-2 leading-normal">
        <div class="text-black font-bold text-md"><%= link_to anime.title, anime_path(anime) %></div>
        <div>
          <p class="text-grey-darker"><%= @comparison.actor1.character(anime)[0]&.name %></p>
          <p class="text-grey-darker"><%= @comparison.actor2.character(anime)[0]&.name %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>