config/routes.rb
Rails.application.routes.draw do
  root to: 'characters#index'
  devise_for :users
  resources :actors
  resources :animes
  resources :characters
  resources :anime_characters
  resources :actor_characters
  get 'messages/new' => 'messages#new'
  post 'messages' => 'messages#create'
  get 'comparisons/index'
  get 'comparisons/show'
end

app/models/actor.rb
class Actor < ApplicationRecord
  validates :sh_name, presence: true

  has_many :actor_characters, dependent: :destroy
  has_many :characters, through: :actor_characters
  has_many :actor_animes, dependent: :destroy
  has_many :anime, through: :actor_animes

  def character(anime)
    characters.select { |character| character.anime.include?(anime) }
  end
end

app/models/actor_anime.rb
class ActorAnime < ApplicationRecord
  validates :actor_id, :anime_id, presence: true
  belongs_to :actor
  belongs_to :anime
end

app/models/actor_character.rb
class ActorCharacter < ApplicationRecord
  validates :actor_id, :character_id, presence: true
  belongs_to :actor
  belongs_to :character
end

app/models/anime.rb
class Anime < ApplicationRecord
  validates :title, presence: true

  has_many :anime_characters, dependent: :destroy
  has_many :characters, through: :anime_characters
  has_many :actor_animes, dependent: :destroy
  has_many :actors, through: :actor_animes
end

app/models/anime_character.rb
class AnimeCharacter < ApplicationRecord
  validates :anime_id, :character_id, presence: true
  belongs_to :anime
  belongs_to :character
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  validates :name, presence: true

  has_many :actor_characters, dependent: :destroy
  has_many :anime_characters, dependent: :destroy
  has_many :actors, through: :actor_characters
  has_many :anime, through: :anime_characters

  def actor(anime)
    actors.select { |actor| actor.anime.include?(anime) }
  end

  def s_anime(actor)
    anime.select { |anime| anime.actors.include?(actor) }
  end
end

app/models/comparison.rb
# frozen_string_literal: true

class Comparison
  include ActiveModel::Model
  attr_accessor :actor_ids, :actor1, :actor2
  validates :actor_ids, presence: true, length: { is: 3 }

  def set_actors
    @actor1 = Actor.find(actor_ids[1])
    @actor2 = Actor.find(actor_ids[2])
  end

  def co_animation
    set_actors
    @actor1.anime & @actor2.anime
  end
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :account, :body
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :set_actor, only: %i[show edit update destroy]
  def index
    @q = Actor.ransack(params[:q])
    @actors = @q.result(distinct: true).page(params[:page])
  end

  def show; end

  def edit; end

  def update
    if @actor.update(actor_params)
      redirect_to @actor, notice: 'successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @actor.destroy
    redirect_to root_path
  end

  private

  def set_actor
    @actor = Actor.find(params[:id])
  end

  def actor_params
    params.require(:actor).permit(:name)
  end
end

app/controllers/animes_controller.rb
class AnimesController < ApplicationController
  before_action :set_anime, only: %i[show edit update destroy]

  def index
    @q = Anime.ransack(params[:q])
    @animes = @q.result(distinct: true).page(params[:page])
  end

  def show; end

  def edit; end

  def update
    if @anime.update(anime_params)
      redirect_to @anime, notice: 'successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @anime.destroy
    redirect_to root_path
  end

  private

  def set_anime
    @anime = Anime.find(params[:id])
  end

  def anime_params
    params.require(:anime).permit(:title)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    if @message.valid?
      MessageMailer.contact(@message).deliver_now
      flash[:notice] = "メッセージを送ってくださりありがとうございます。改善に役立てます。"
      redirect_to root_path
    else
      flash[:notice] = "内容を記入してください。"
      render :new
    end
  end

  private

  def message_params
    params.require(:message).permit(:account, :body)
  end
end

app/helpers/actor_characters_helper.rb
module ActorCharactersHelper
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/anime_characters_helper.rb
module AnimeCharactersHelper
end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/comparisons_helper.rb
module ComparisonsHelper
end

app/views/layouts/_header.html.erb
<nav class="flex items-center justify-between flex-wrap bg-grey-darkest p-4">
  <div class="flex items-center justify-between text-white">
    <div class="flex items-center flex-no-shrink">
      <span class="font-semibold text-xl tracking-tight"><%= link_to 'baker', root_path, class: 'text-white' %></span>
      <p class="ml-2 text-sm">-声優/キャラ/アニメの検索サービス</p>
    </div>
  </div>
  <div>
    <% if user_signed_in? && current_user.admin? %>
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'text-white' %>
    <% end %>
    <%= link_to 'お問い合わせ', messages_new_path, class: 'text-white mt-4 lg:mt-0' %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Baker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <%= favicon_link_tag('favicon.png') %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss/dist/tailwind.min.css" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= analytics_init if Rails.env.production? %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% if flash[:notice] %>
      <div class="w-full text-center p-4 mx-auto">
        <%= flash[:notice] %>
        <%= alert %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>